Escape menu is added the game
cagdasgerede/JavaFX-Tetris-Clone pull request #13
Opened 2020-12-06 11:41 UTC by safaergnn

Escape Menu which includes Settings - Load - Save - ScoreBoard - Exit windows are added.

2020-12-06 18:04 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/MenuFrame.java
> +}
add newline

2020-12-06 18:04 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/MenuPanel.java
> +
remove extra space

2020-12-06 18:05 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/MenuPanel.java
> +				focusIndex = (focusIndex + menus.length - 1) % menus.length;
Fix indentation

2020-12-06 18:05 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/MenuPanel.java
> +	//Son kaydedilen oyun ekranı matrisini ve skorunu geri yükleyen metot...
Use English

2020-12-06 18:06 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/ScoreBoardPanel.java
> +}
add newline

2020-12-06 18:06 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SettingsMenuPanel.java
> +	private int[] menu_ys = new int[] { 80, 110, 140, 170 };
fix indentation

2020-12-06 18:06 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SettingsMenuPanel.java
> +		this.setFocusable(true);
fix indentation

2020-12-06 18:06 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SpeedSettingsMenuPanel.java
> +			if(keyCode == KeyEvent.VK_UP || keyCode == KeyEvent.VK_W){  // up direction key
fix indentation

2020-12-06 18:07 UTC, cagdasgerede commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
add this file to .gitignore and remove from the PR

2020-12-06 18:07 UTC, cagdasgerede commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
add this file to .gitignore and remove from the PR

2020-12-06 18:07 UTC, cagdasgerede commented on .settings/org.eclipse.core.resources.prefs
> +eclipse.preferences.version=1
add this file to .gitignore and remove from the PR

2020-12-06 18:07 UTC, cagdasgerede commented on .settings/org.eclipse.jdt.apt.core.prefs
> +eclipse.preferences.version=1
add this file to .gitignore and remove from the PR

2020-12-06 18:07 UTC, cagdasgerede commented on .settings/org.eclipse.jdt.core.prefs
> +eclipse.preferences.version=1
add this file to .gitignore and remove from the PR

2020-12-06 18:07 UTC, cagdasgerede commented on .settings/org.eclipse.m2e.core.prefs
> +activeProfiles=
add this file to .gitignore and remove from the PR

2020-12-06 18:08 UTC, cagdasgerede commented
buraya yaptığın değişikliği demo ettiğin bir videoyu ekle.

2020-12-06 18:09 UTC, cagdasgerede requested changes
Needs more work

2020-12-07 20:04 UTC, cagdasgerede commented
This PR contains files that should not be here. Remove them. The PR should only have the code changes you have done.

2020-12-07 21:46 UTC, safaergnn commented
Demo link : https://www.youtube.com/watch?v=MLgx_v0kOvo

2020-12-12 15:16 UTC, cagdasgerede commented on .gitignore
> +.settings/
missing newline

2020-12-12 15:16 UTC, cagdasgerede commented on pom.xml
> +        <groupId>org.wso2.carbon</groupId>
Bu ne için kullanılıyor?

2020-12-12 15:17 UTC, cagdasgerede commented on src/main/java/com/quirko/app/GameController.java
> +    public static  GuiController viewGuiController;
Instead of defining this as public, implement an accessor method and call that method.

2020-12-12 15:18 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/GuiController.java
>  import com.quirko.logic.DownData;
Buradaki importların sırası hatalı. İmport sırasını düzelt lütfen.

2020-12-12 15:18 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/GuiController.java
> +    public static Timeline timeLine;
Yukarıda bahsettiğim durumla aynı durum. Burayı da aynı şekilde düzelt.

2020-12-12 15:20 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SettingsMenuPanel.java
> +		this.setFocusable(true);
Bu dosyadaki indentation sorunlarını halen düzeltmemişsin.

2020-12-12 15:21 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SettingsMenuPanel.java
> +				focusIndex = (focusIndex + menus.length - 1) % menus.length; // Consider the meaning of % remainder.
`// Consider the meaning of % remainder.` ? 
Bu comment ile ne demek istediğin anlaşılmıyor.

2020-12-12 15:21 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SettingsMenuPanel.java
> +			case KeyEvent.VK_UP:// up direction key
Zaten VK_UP dediğin için up olduğu anlaşılıyor. Comment e gerek yok.

2020-12-12 15:21 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SettingsMenuPanel.java
> +			case KeyEvent.VK_DOWN:// down arrow
gereksiz comment

2020-12-12 15:21 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SettingsMenuPanel.java
> +					gamespeedsettingsmenuframe = new SpeedSettingsFrame();
bozuk indentation

2020-12-12 15:22 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SpeedSettingsMenuPanel.java
> +
gereksiz newline

2020-12-12 15:22 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SpeedSettingsMenuPanel.java
> +	This class is a settings menu.
gereksiz comment

2020-12-12 15:22 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SpeedSettingsMenuPanel.java
> +	private int menu_x = 260;
gereksiz newlinelar

2020-12-12 15:23 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SpeedSettingsMenuPanel.java
> +			//If pressed too slow, it makes the speed 1.
too slow ?

ne demek istiyorsun

2020-12-12 15:25 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SpeedSettingsMenuPanel.java
> +			//If the slow button is pressed, it makes the speed 2.
buradaki commentler yerine değişken isimlerini daha doğru seçersen zaten koddan ne olduğu anlaşılır. 

focusIndex, setRate vs. yerine daha uygun isimler bulunabilir. 

Buradaki if ler yerine bir switch bloğu yaz. Switch bloğunda yalnızca hızı güncelle.

En sonda da bir tane şöyle block yaz.

```
SettingsMenuPanel.gamespeedsettingsmenuframe.dispose();
GuiController.timeLine.setRate(speed);
```

2020-12-12 15:26 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SpeedSettingsMenuPanel.java
> +		if(keyCode == KeyEvent.VK_DOWN || keyCode == KeyEvent.VK_S){  // down arrow
else if

2020-12-12 15:26 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SpeedSettingsMenuPanel.java
> +		if(keyCode == KeyEvent.VK_ENTER){ // Enter key
else if

2020-12-12 15:26 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SpeedSettingsMenuPanel.java
> +		if(keyCode == KeyEvent.VK_ESCAPE){ //Escape Key
else if

2020-12-12 15:27 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/SimpleBoard.java
> +    public static int[][] currentGameMatrix;
Diğer dosyalarda bahsettiğim gibi bunları  public yapmak yerine accessor metotları implement et.

2020-12-12 15:28 UTC, cagdasgerede requested changes
Needs more work. See my comments in the code.

Ayrıca gönderdiğin videoda sesli herhangi bir anlatım yok. Videoyu seslendirerek tekrar çek.

2020-12-13 12:43 UTC, safaergnn commented
Demo Link : https://www.youtube.com/watch?v=6Syh9rLM8GA&feature=youtu.be

2020-12-14 15:26 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/GuiController.java
> +        if(isGameOver.get() == Boolean.TRUE){
Bu kısımla ilgili başka bir issue var ve onu başka bir arkadaşın yapıyor. Bu kısmı boş bırak. O arkadaşının senin PRın merge olduktan sonra ikinci bir PR ile buraya entegre olması gerekecek.

2020-12-14 15:29 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/SettingsMenuPanel.java
> +		this.setTitle("Settings Menu");
Burayı başka bir issue hallediyor. Senin issue'nda template yaz diyor. Speed ayarları gibi bir istek yok.

Pencere kalsın ama boş göstersin. Speed settings kısmını sil.

2020-12-14 15:32 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/MenuPanel.java
> +	public void loadScore() throws IOException {
Bu kısım başka bir issue da isteniyor. Bu kısmı boş bırak.

Sen yalnızca şablon olarak bırakacaksın burayı. O arkadaşın buraya daha sonra entegre olacak. Örneğin dosya ismi seçme, birden fazla save alma, automatic save almalar vs. gibi konular geçebilir o issueda. Bu kadar tek düze olması şart değil load/save kodunun.

2020-12-14 15:32 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/ScoreBoardPanel.java
> +    It is the class that creates a window showing the scores.
Gereksiz yorum

2020-12-14 15:33 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/ScoreBoardPanel.java
> +        columns =new String[2];
Score için de başka bir issue tanımlı. Şimdilik böyle kalabilir ama burası da burakinden daha kapsamlı şekilde implement edilmesi gerekiyor. 

Daha sonra o implementasyon buraya entegre olacak.

2020-12-14 15:34 UTC, cagdasgerede requested changes
See my comments.

2020-12-21 09:20 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/GuiController.java
> +            e.printStackTrace();
Bu tür exceptionları log objesine logla.

2020-12-21 09:28 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/MenuPanel.java
> +			if(e.getSource() == settings){
actionPerformed içini bir metoda taşı. Verilen source'a göre doğru metot çağırılıyor mu mockitoyu da kullanarak mock veya spy obje kullanarak verify et.

Şunu da bir metota taşı: "new SettingsMenuPanel() "

Daha sonra bu yeni metot için şöyle unit testler yaz:

settings source olduğunda -> createSettingsMenu() çağırılıyor
load source olduğunda -> load() çağırılıyor
save source olduğunda -> save() çağırılıyor
vb.

verify et.

2020-12-21 09:29 UTC, cagdasgerede requested changes
Kodlarını bıraktığım notlara göre güncelle.

Bir de yorumlara cevap verip Resolve Converation düğmesine basmayı unutma.

Review etmemi istediğinde bana assign etmeyi unutma.

2021-03-22 23:56 UTC, closed without merging