Feature/#11 add special brick
cagdasgerede/JavaFX-Tetris-Clone pull request #14
Opened 2020-12-10 18:11 UTC by CanKocyigitoglu

As requested in issue 11, I added a special Brick that can be changed by the players to existing any other Bricks. Also, A sound played when the special brick appears.

2020-12-11 12:19 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/AudioHandler.java
> +package com.quirko.logic;
Bu kodu bir yerden mi aldın? Eğer öyleyse dosyanın başına nereden olduğunu belirt.

2020-12-11 12:19 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/AudioHandler.java
> +	/** Website too look at: www.javalobby.org/java/forums/t18465.html */
? Ne için bu sayfaya bakacağız. Bu sayfa açılmıyor. Bu dosyayı doğrudan bir yerden copy/paste mi ettin

Ayrıca `too` => `to` olacak

2020-12-11 12:20 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/AudioHandler.java
> +}
Add newline

2020-12-11 12:21 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/SimpleBoard.java
> +            audio.load("selection.wav", "select");
Bu ses dosyasının bir kaynak adresi var mı? Kendin mi yaptın?

2020-12-11 12:22 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/bricks/DotBrick.java
> +public class DotBrick implements Brick {
DotBrick bir şey ifade etmiyor. Ne manaya geldiğini class başına comment ile anlatabilir misin?

2020-12-11 12:23 UTC, cagdasgerede requested changes
Yaptığın değişiklikleri anlatan bir videonun linkini PR threadine ekle.

Yaptığın değiliklikler için test yaz.

2020-12-11 12:31 UTC, CanKocyigitoglu commented on src/main/java/com/quirko/logic/SimpleBoard.java
> +            audio.load("selection.wav", "select");
Bu kısımı AudioHandler sayfasını aldığım yerden bakarak kendim yazdım yine de kaynak adresi vermeli miyim?

2020-12-11 12:31 UTC, CanKocyigitoglu commented on src/main/java/com/quirko/logic/AudioHandler.java
> +	/** Website too look at: www.javalobby.org/java/forums/t18465.html */
Evet hocam kaynak belirtmeye çalışacağım.

2020-12-12 22:01 UTC, CanKocyigitoglu reviewed
ilk video: https://www.youtube.com/watch?v=OfqztV0mM80&ab_channel=CanKo%C3%A7yi%C4%9Fito%C4%9Flu

2020-12-12 22:01 UTC, CanKocyigitoglu commented on src/main/java/com/quirko/logic/AudioHandler.java
> +package com.quirko.logic;
Hocam video sahibinin youtube kanalında bilgileri yok. Yönlendirdiği sayfa ise erişime kapalı. Ben de böyle bir çare buldum.

2020-12-13 11:50 UTC, CanKocyigitoglu commented on src/main/java/com/quirko/logic/AudioHandler.java
> +}
done

2020-12-13 11:51 UTC, CanKocyigitoglu commented on src/main/java/com/quirko/logic/SimpleBoard.java
> +            audio.load("selection.wav", "select");
done

2020-12-13 11:51 UTC, CanKocyigitoglu commented on src/main/java/com/quirko/logic/bricks/DotBrick.java
> +public class DotBrick implements Brick {
done

2020-12-13 11:51 UTC, CanKocyigitoglu commented on src/main/java/com/quirko/logic/AudioHandler.java
> +	/** Website too look at: www.javalobby.org/java/forums/t18465.html */
done

2020-12-14 16:22 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/AudioHandler.java
> +package com.quirko.logic;
Hangi videodan bahsediyorsun?

2020-12-14 16:29 UTC, cagdasgerede commented on src/test/java/com/quirko/logic/bricks/DotBrickTest.java
> +        Brick brick = new DotBrick();
Bu neyi test ediyor? DotBrick matrixinde bir yer hariç her yerin sıfır olduğunu yani şeklinin nokta olduğunu test ediyorsun galiba.

Buradaki testleri arttır. DotBrick'in başka şekillere doğru şekilde dönüştürüldüğünün testi yok örneğin. Test kısmına biraz daha kafa yor.

2020-12-14 16:30 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/SimpleBoard.java
> +    public boolean changeBrick() {
Bu methodu test etmiyorsun.

2020-12-14 16:34 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/SimpleBoard.java
> +            brickRotator.setBrick(currentBrick);
Demo sırasında işini kolaylaştırmak için uygulama belli bir flag ile çalıştırıldıktan sonra, oyun sırasında belli bir keye basıldığında bu özel brickin gelmesini sağla. Böylece istediğin zaman demoda bir dotbrick çıkartabilirsin.

2020-12-14 16:35 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/AudioHandler.java
> +/** Author: Full name of Author is unknown. Here is the youtube channel and source code of author:
Başka yerden aldığın tüm dosyaları thirdparty diye bir klasör oluşturup oraya at.

`src/main/java/com/quirko/logic/AudioHandler.java` => `src/main/java/com/quirko/thirdparty/AudioHandler.java`

2020-12-14 16:36 UTC, cagdasgerede requested changes
Kod içerisinde baktığım notlara göre kodunu güncelle.

2020-12-14 18:06 UTC, CanKocyigitoglu commented on src/main/java/com/quirko/logic/AudioHandler.java
> +package com.quirko.logic;
Hocam kaynağı bulamadan önce koymuştum bu yorumu kaynağı buldum. Ama video linkini yine de ekleyeceğim. comment satırı olarak

2020-12-16 11:42 UTC, CanKocyigitoglu commented
https://www.youtube.com/watch?v=gQoHmOOsoGA&ab_channel=CanKo%C3%A7yi%C4%9Fito%C4%9Flu

2020-12-20 02:15 UTC, cagdasgerede commented on src/main/java/com/quirko/thirdparty/AudioHandler.java
> +			c.open(decodedIn);
fix indentation.

2020-12-20 02:17 UTC, cagdasgerede commented on src/main/java/com/quirko/thirdparty/AudioHandler.java
> +			e.printStackTrace();
Bu tür exceptionları log dosyasına logla

2020-12-20 02:18 UTC, cagdasgerede commented on src/main/java/com/quirko/thirdparty/AudioHandler.java
> +			e1.printStackTrace();
logla

2020-12-20 02:18 UTC, cagdasgerede commented on src/main/java/com/quirko/thirdparty/AudioHandler.java
> +			e1.printStackTrace();
logla

2020-12-20 02:18 UTC, cagdasgerede commented on src/main/java/com/quirko/thirdparty/AudioHandler.java
> +				e.printStackTrace();
logla

2020-12-20 08:57 UTC, cagdasgerede commented on src/test/java/com/quirko/logic/bricks/DotBrickTest.java
> +    /**Tests changeBrick method in SimpleBoard Class */
Gereksiz comment.

2020-12-20 08:58 UTC, cagdasgerede commented on src/test/java/com/quirko/logic/bricks/DotBrickTest.java
> +    public void testChangeBrick() throws Exception {
Bu metodun yeri SimpleBoardTest.java dosyası.

2020-12-20 08:59 UTC, cagdasgerede commented on src/test/java/com/quirko/logic/bricks/DotBrickTest.java
> +    public void testChangeNextBrick() throws Exception {
Bu metotun yeri RandomBrickGenerator.java

2020-12-20 09:04 UTC, cagdasgerede requested changes
Kodlarını bıraktığım notlara göre güncelle.

Jacoco'yu çalıştır ve jacoco raporundan DotBrick.java ve AudioHandler.java dosyalarının jacoco raporundan screenshotlarını Threadte paylaş.

Review etmemi istediğinde bana assign etmeyi unutma.

2021-03-22 23:56 UTC, closed without merging