Started working on achievements
cagdasgerede/JavaFX-Tetris-Clone pull request #15
Opened 2020-12-11 17:37 UTC by efeka

2020-12-19 08:25 UTC, cagdasgerede commented on src/main/java/com/quirko/app/GameController.java
> +            //check line clear related achievements
gereksiz comment

2020-12-19 08:26 UTC, cagdasgerede commented on src/main/java/com/quirko/app/GameController.java
> +                //check score related achievements
gereksiz comment

2020-12-19 08:26 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/GuiController.java
> +            //display achievements when they are completed
gereksiz comment

2020-12-19 08:28 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/Achievements.java
> +}
missing newline

2020-12-19 08:28 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/DownData.java
> +    private final Achievements achievement;
```Achievements achivements```

2020-12-19 08:33 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/Achievements.java
> +        totalLinesCleared += lines;
Bu toplam rakam, uygulama her acilip kapandiginda sifirlanir. Bu achievementlari bir dosyaya persist etmen lazim. Her uygulama acildiginda da bu achievementlari okuman lazim. Aksi halde bu achievementlar sadece her yeni oyun acilisi boyunca gecerli olur.

2020-12-19 08:38 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/Achievements.java
> +public class Achievements {
Bu classtan subclasslar yaz. Her subclassin adi ne tur bir achievement ise onu yansitsin.

Ortak kodlar Achivement classinda olsun. Achivement classinda isAchieved gibi boolean donen bir metot tanimlanabilir. Subclasslar bunu override edebilir.

2020-12-19 08:43 UTC, cagdasgerede requested changes
Achivement lari bir class hiyerarsisi icerisinde tanimla. Achievement diye bir class olsun ve specific achievementlar bu classin sublcasslari olsunlar. Achivementlar oyun kapatilip acilinca da dogru track edilmeye devam etsinler. Bunun icin achivementlari bir dosyaya persist etmen lazim.

Her achivement tipi icin unit testler yaz.

Ayrica su ana kadar yaptigin degisiklikleri anlatan bir videonun linkini burada paylas.

2020-12-19 17:39 UTC, efeka commented
Hocam bir sonraki pushumda unit testler de olacak. İstediğiniz videoyu henüz çekemedim, şimdi kodun söylediğiniz zamandaki versiyonuna göre mi çekeyim yoksa şimdiki haline mi? Yoksa ikisi birden mi?

2020-12-21 09:40 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/achievements/AchievementFileIO.java
> +        try {
fix indentation

2020-12-21 09:41 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/achievements/AchievementFileIO.java
> +		} catch (Exception e) {
fix indentation

2020-12-21 09:41 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/achievements/AchievementFileIO.java
> +            e.printStackTrace();
Bu tür exceptionları log dosyasına logla.

2020-12-21 09:41 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/achievements/AchievementFileIO.java
> +            System.out.println(userAchievements);
kodda sysout görmek istemiyorum.

2020-12-21 09:41 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/achievements/Achievements.java
> +}
missing newline

2020-12-21 09:42 UTC, cagdasgerede commented on src/main/java/com/quirko/logic/achievements/TotalLinesCleared.java
> +}
missing newline

2020-12-21 09:43 UTC, cagdasgerede commented on src/main/resources/user_achievements.txt
> +a
Bu dosyayı repoya eklemeye gerek var mı?

2020-12-21 09:45 UTC, cagdasgerede requested changes
Genel olarak achivement hiyerarşisi uygun.

Yaptıklarını görsel olarak gösteren bir videoyu bekliyorum halen. Aynı zamanda kodun için herhangi bir test yazmamışsın. Bir sonraki commitinde manalı unit testler de ekle lütfen.

Review etmemi istediğinde bana assign etmeyi unutma.

2020-12-22 09:04 UTC, efeka commented
Merhaba hocam, istediğiniz videoyu çektim.
https://www.youtube.com/watch?v=y2KKuR5ztfU&ab_channel=efekaraman

2021-03-22 23:56 UTC, closed without merging