added save/load option
cagdasgerede/JavaFX-Tetris-Clone pull request #18
Opened 2020-12-15 11:49 UTC by ahmedtahas

2020-12-15 13:29 UTC, cagdasgerede commented on .classpath
> +<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
.classpath dosyasini .gitignore'a ekle be bu dosyayı PRdan sil. Bu tür dosyalar senin kendi development environmentın ile ilgili dosyalar ve bu tür dosyalar code repoda tutulmaz.

2020-12-15 13:29 UTC, cagdasgerede commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
ditto

2020-12-15 13:29 UTC, cagdasgerede commented on .settings/org.eclipse.core.resources.prefs
> +eclipse.preferences.version=1
ditto

2020-12-15 13:29 UTC, cagdasgerede commented on .settings/org.eclipse.jdt.apt.core.prefs
> +eclipse.preferences.version=1
ditto

2020-12-15 13:29 UTC, cagdasgerede commented on .settings/org.eclipse.jdt.core.prefs
> +eclipse.preferences.version=1
ditto

2020-12-15 13:29 UTC, cagdasgerede commented on bin/.gitignore
> +.idea
ditto

2020-12-15 13:30 UTC, cagdasgerede commented on bin/.project
> +<?xml version="1.0" encoding="UTF-8"?>
ditto

2020-12-15 13:30 UTC, cagdasgerede commented on bin/README.md
> +JavaFX Tetris Clone Game
bin/ klasörünün altındaki hiçbir dosya repoda olmamalı. Tüm bin klasörünü .gitignore dosyasına ekle.

2020-12-15 13:32 UTC, cagdasgerede commented on src/main/java/com/quirko/app/GameController.java
> +
gereksiz newline

2020-12-15 13:32 UTC, cagdasgerede commented on src/main/java/com/quirko/app/GameController.java
> +        //System.out.println(board.getViewData().getxPosition() + " AAAAAAAA");
sil

2020-12-15 13:34 UTC, cagdasgerede commented on src/main/java/com/quirko/app/GameController.java
> +        String boardMatrix = "", currentShape = "", nextShape = "", posX = "" + getPosX(), posY = "" +  getPosY(), score = "" +  getScore();
Bu implementasyonu yeni bir klass içerisine taşı. Buraya eklediğin kod GameController classını gereğinden fazla şişiriyor ve okunaklılığını azaltıyor.

2020-12-15 13:35 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/GuiController.java
> +        path = System.getProperty("user.dir") + File.separator + "saves";
Kullanıcı istediği klasörü seçebilsin. Bu şekilde yalnızca sabit bir yere kaydedilmesin.

2020-12-15 13:35 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/GuiController.java
> +                        FileChooser.ExtensionFilter("textfile", "*.txt"));
fix indentation

2020-12-15 13:36 UTC, cagdasgerede commented on src/main/java/com/quirko/gui/GuiController.java
> +                    {
Curly bracket kullanımı consistent değil. 

```
if (...)
{
```
=>
```
if(...) {
```

2020-12-15 13:40 UTC, cagdasgerede requested changes
Kod içerisine bıraktığım notlara göre kodunu güncelle.

Ayrıca "bin/" klasörünün altındaki hiçbir dosya repoda olmamalı. "bin/" ifadesini .gitignore dosyasına ekle ve PRından bu klasör altındaki dosyaları sil.

Save kullanıcının seçtiği herhangi bir klasöre yapılabilir olmalı. Ayrıca autosave özelliğini ekle. Arasıra otomatik olarak save etsin oyun kendini. Load ederken de hem manual save edilmiş oyunlar hem de autosave edilmiş son oyun seçenek olarak yer alsın.

Şu ana kadar eklediğin özellikleri anlatan bir videonun linkini PR threadinde paylaş.

Ayrıca eklediğin özelliklerle ilgili herhangi bir test göremiyorum. Yeni özelliklerin doğru çalışıp çalışmadığını kontrol eden manalı testler ekle.

2020-12-15 19:34 UTC, ahmedtahas commented on src/main/java/com/quirko/gui/GuiController.java
> +        path = System.getProperty("user.dir") + File.separator + "saves";
hocam bu zaten default klasor, istedigi yere gidebilir.

2020-12-15 19:40 UTC, ahmedtahas commented
Hocam aklima gercekten hic test gelmiyo. Sizin aklinizda varsa, sunu test et dediginiz, soyleyin implement etmeye calisayim.

2020-12-21 15:00 UTC, ahmedtahas commented
https://www.youtube.com/watch?v=WprR8LR7xfg
projede yaptiklarimin videosu

2021-03-22 23:56 UTC, closed without merging